# Generated by Django 5.0.6 on 2025-03-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abarrotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_abarrotes', models.ImageField(blank=True, null=True, upload_to='abarrotes/', verbose_name='Imagen del Producto')),
                ('nombre_producto', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Producto')),
                ('descripcion_producto', models.TextField(blank=True, null=True, verbose_name='Descripción del Producto')),
            ],
            options={
                'verbose_name': 'Abarrote',
                'verbose_name_plural': 'Abarrotes',
            },
        ),
        migrations.CreateModel(
            name='Pastillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_pastillas', models.ImageField(blank=True, null=True, upload_to='pastillas/', verbose_name='Imagen del Producto')),
                ('nombre_pastillas', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('precio_pastillas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Producto')),
                ('descripcion_pastillas', models.TextField(blank=True, null=True, verbose_name='Descripción del Producto')),
            ],
            options={
                'verbose_name': 'Pastilla',
                'verbose_name_plural': 'Pastillas',
            },
        ),
    ]
